version: '3.9'
services:
  app:
    build: .
    volumes:
      - .:/django
    image: app:django
    container_name: django_container
    env_file:
      - ./.env
    command: gunicorn posting_service.wsgi:application --bind 0.0.0.0:8000

volumes:
  static_volume: