# Generated by Django 4.1.2 on 2022-10-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="nickname",),
    ]
