# Generated by Django 4.1.2 on 2022-10-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                default=1, max_length=10, unique=True, verbose_name="사용자 닉네임"
            ),
            preserve_default=False,
        ),
    ]
