# Generated by Django 4.1.2 on 2022-10-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_groups_user_is_superuser_user_user_permissions_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="groups",),
        migrations.RemoveField(model_name="user", name="is_superuser",),
        migrations.RemoveField(model_name="user", name="user_permissions",),
    ]
