# Generated by Django 4.1.2 on 2022-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="university_score",
            field=models.PositiveIntegerField(default=0, verbose_name="선호대학교 점수"),
        ),
    ]
